CREATE DATABASE bd_curriculo;

USE bd_curriculo;

CREATE TABLE tb_usuario(
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	nome VARCHAR(45) NOT NULL,
	email VARCHAR(120) NOT NULL,
	cpf VARCHAR(14) NOT NULL,
	senha VARCHAR(20) NOT NULL,
	foto VARCHAR(20),
	status VARCHAR(120)
);

CREATE TABLE tb_contato (
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
	telefone VARCHAR(45) NOT NULL, 
	logradouro  VARCHAR(240) NOT NULL,
	numero VARCHAR(10) NOT NULL,
	bairro VARCHAR(100) NOT NULL
);

CREATE TABLE tb_cidade(
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	nome VARCHAR(250) NOT NULL
);

CREATE TABLE tb_estado(
	id_estado INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	sg_estado VARCHAR(2) NOT NULL
);

CREATE TABLE tb_escolaridade(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nome VARCHAR(45) NOT NULL 
);

CREATE TABLE tb_experiencia(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	dt_inicio DATE NOT NULL,
	dt_termino DATE NOT NULL
);

CREATE TABLE tb_habilidade(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
	nome VARCHAR(45)
);

CREATE TABLE tb_curriculo(
	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL
);